server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432/lab4_web}
    username: ${DB_USERNAME:stepan}
    password: ${DB_PASSWORD:postgres}

  jpa:
#    generate-ddl: true
    show-sql: false
