server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5433/postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    generate-ddl: true
    show-sql: false